routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// others
Route::get('/coming_soon','GuestController@web_coming_soon')->name('coming_soon');
Route::get('pages/testing','GuestController@page_test');
Route::get('pages/ebay','AdminController@ebay')->middleware('admin');
Route::get('/test','GuestController@test')->middleware('admin');
Route::get('/test1','GuestController@test1')->middleware('admin');
Route::get('/g_code','GuestController@g_code')->middleware('admin');
Route::get('/pick_code','GuestController@pick_code')->middleware('admin');
Route::get('/send_sms/{phone}/{text}','AdminController@send_sms');
Route::get('/test2/{query}','GuestController@test2');

// public info page
Route::prefix('official')->group(function(){
    Route::get('about_us','PublicController@about_us');
    Route::get('contact_us','PublicController@contact_us');
});
// public coming soon page
Route::namespace('User')->prefix('others')->group(function(){
    Route::get('coming_soon','InfoController@coming_soon');
});

/**
 * Guest Routes
 */
Auth::routes();
Route::post('/send_code','GuestController@send_code');
Route::get('/', 'HomeController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('index');
Route::get('mall/payment_result/{user_id}/{trade_id}', 'GuestController@payment_result');


/**
 * User routes
 */
/*
 * Organized User Routes
 */
Route::middleware(['mobile','not_staff'])->group(function(){
    /* related to user settings */
    Route::namespace('User')->middleware(['auth','not_staff'])->group(function(){
        Route::post('disable_welcome','UserController@disable_welcome')->name('users.disable_welcome');
        Route::post('disable_delivery_reminder','UserController@disable_delivery_reminder')->name('users.disable_delivery_reminder');

        /* edit password */
        Route::get('edit_password','UserController@edit_password')->name('home_edit_password');
        Route::post('change_password','UserController@change_password')->name('home_change_password');
    });

    /* Shopping Mall */
    Route::prefix('mall')->group(function(){
        Route::namespace('User')->group(function(){
            /* Main Tabs */
            Route::get('home', 'HomeController@home')->name('home_home');
            Route::get('products', 'HomeController@products')->name('home_products');
            Route::get('brands', 'HomeController@brands')->name('home_brands');
            Route::get('gift_center', 'HomeController@gift_center')->name('home_gift_center');
            Route::get('shopping_cart', 'HomeController@shopping_cart')->name('home_cart');
            Route::get('dashboard', 'HomeController@dashboard')->name('home_dashboard');

            /* shopping cart actions */
            Route::get('get_shopping_cart', 'CartController@get_cart_products');
            Route::post('add_to_cart','CartController@add_to_cart');
            Route::post('update_cart', 'CartController@update_cart');
            Route::delete('remove_from_cart','CartController@remove_from_cart');
            Route::delete('clear_cart', 'CartController@clear_cart');
            Route::get('select_package_method','CartController@select_package_method')->name('home_select_package_method')->middleware(['auth','not_staff']);
            Route::post('create_order', 'CartController@create_order')->name('home_create_order')->middleware(['auth','not_staff']);

            /* addresses */
            Route::middleware(['auth','not_staff'])->group(function(){
                Route::get('addresses', 'AddressController@address_index')->name('home_address_index');
                Route::get('get_sending_addresses', 'AddressController@get_sending_addresses');
                Route::post('addresses/new', 'AddressController@address_new');
                Route::delete('delete_sending_address', 'AddressController@delete_sending_address');
                Route::get('get_sender_addresses', 'AddressController@get_sender_addresses');
                Route::post('sender_addresses/new', 'AddressController@sender_address_new');
                Route::delete('delete_sender_address', 'AddressController@delete_sender_address');
            });

            /* orders */
            Route::middleware(['auth','not_staff'])->group(function(){
                Route::get('orders', 'OrderController@order_index')->name('home_order_index');
                Route::get('get_all_orders', 'OrderController@all_orders');
                Route::get('show_order/{id}', 'OrderController@order_show')->name('home_order_show');
                Route::get('get_unpaid_orders', 'OrderController@unpaid_orders');
                Route::get('get_paid_orders', 'OrderController@paid_orders');
                Route::get('get_sending_orders', 'OrderController@sending_orders');
                Route::get('get_completed_orders', 'OrderController@completed_orders');
                Route::post('confirm_order', 'OrderController@confirm_order');
                Route::post('create_transaction','OrderController@create_payment');
                Route::get('track_delivery/{delivery_no}','OrderController@track_delivery');
            });

            /* product page */
            Route::get('products/{id}', 'ProductController@product_show')->name('home_product_show');
            Route::get('get_product/{id}', 'ProductController@get_product');
            Route::get('products/detail/{id}','ProductController@product_detail');
            Route::post('search_products', 'ProductController@search_products')->name('home_search_products');
            Route::post('products/update_like', 'ProductController@update_like')->middleware(['auth','not_staff']);
            Route::get('favourites', 'ProductController@favourite_index')->name('home_favourite_index')->middleware(['auth','not_staff']);
            Route::get('get_fav', 'ProductController@get_fav')->middleware(['auth','not_staff']);

            /* collection page */
            Route::get('collections/{id}','CollectionController@collection_show')->name('home.collections.show');

            /* category page */
            Route::get('categories/{id}', 'CategoryController@category_show')->name('home_category_show');

            /* brand page */
            Route::get('brands/{id}', 'BrandController@brand_show')->name('home_brand_show');
            Route::get('get_other_brands','BrandController@get_other_brands');

            /* service page */
            Route::middleware(['auth','not_staff'])->group(function(){
                Route::get('services', 'ServiceController@service_index')->name('home_service_index');
                Route::get('services/create/{order_id}', 'ServiceController@service_create')->name('home_service_create');
                Route::post('services/store', 'ServiceController@service_store')->name('home_service_store');
                Route::get('services/{service_id}', 'ServiceController@service_show')->name('home_service_show');
            });
        });

        /* info routes */
        Route::namespace('User')->group(function(){
            Route::get('questions','InfoController@questions')->name('users.info.questions');
            Route::get('about_us','InfoController@about_us')->name('users.info.about_us');
            Route::get('contact_us','InfoController@contact_us')->name('users.info.contact_us');
        });

    });

    /* 银豹 stock */
    Route::get('/get_inventory_by_id/{id}','PospalController@get_inventory_by_id');
});



/**
 * Admin routes
 */
Route::middleware('admin')->group(function (){
    /* routes for user model */
    Route::resource('users', 'UserController');

    /* products */
    Route::prefix('products')->group(function(){
        Route::get('trashed','ProductController@index_trashed')->name('products.index_trashed');
        Route::post('restore/{id}','ProductController@restore')->name('products.restore');
        Route::get('sort/{order}','ProductController@sort')->name('products.sort');
    });
    Route::resource('products', 'ProductController');

    /* collections */
    Route::prefix('collections')->group(function(){
        Route::get('/','CollectionController@index')->name('collections.index');
        Route::get('show/{id}','CollectionController@show')->name('collections.show');
        Route::get('create','CollectionController@create')->name('collections.create');
        Route::post('store','CollectionController@store')->name('collections.store');
        Route::get('edit/{id}','CollectionController@edit')->name('collections.edit');
        Route::patch('update/{id}','CollectionController@update')->name('collections.update');
        Route::post('collections/update_products/{id}','CollectionController@update_products')->name('collections.update_products');

    });

    /* categories */
    Route::prefix('categories')->group(function(){
        Route::get('order','CategoryController@order')->name('categories.order');
    });
    Route::resource('categories', 'CategoryController');

    /* brands */
    Route::prefix('brands')->group(function (){
        Route::get('orders/show','BrandController@show_order')->name('brands.order');
        Route::post('orders/change','BrandController@change_order')->name('change_brand_order');
        Route::get('sort/{order}','BrandController@sort')->name('brands.sort');
    });
    Route::resource('brands', 'BrandController');

    /* routes for staff */
    Route::prefix('staffs')->group(function (){
        Route::get('/', 'UserController@staff_index')->middleware('admin')->name('staff_index');
        Route::get('create', 'UserController@staff_create')->middleware('admin')->name('staff_create');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ShoppingCart;
use App\OrderProduct;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;

class Product extends Model
{
    protected $fillable =['name','description','price','weight','brand_id','category_id','sale','img_url','pospal_id','real_sale','spec','RRP','sale_price','reward_points','expired_date'];

    use SoftDeletes;
    use Searchable;

    protected $hidden = [
        'real_sale','pospal_id','reward_points'
    ];

    protected $dates = ['deleted_at'];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function brand(){
        return $this->belongsTo('App\Brand');
    }

    public function get_cart_quantity($user_id){
        return ShoppingCart::where('user_id', $user_id)->
            where('product_id',$this->id)->firstOrFail()->quantity;
    }

    public function get_order_quantity($order_id){
        return OrderProduct::where('order_id', $order_id)->
            where('product_id',$this->id)->firstOrFail()->quantity;
    }

    public function searchableAs()
    {
        return 'name';
    }

    public function collection(){
        return $this->belongsToMany('App\Collection','collection_products');
    }

}

app/Http/Controllers/User/ProductController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\Product;
use App\Brand;
use App\Category;
use App\Favourite;

class ProductController extends Controller
{
    /**
     * render single product page, includes brand, category and favourite/likes
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function product_show(Request $request)
    {
        $user = Auth::user();
        $page = "products";
        $product = Product::find($request->id);
        $product['brand'] = Brand::find($product->brand_id);
        $product['category'] = Category::find($product->category_id);
        if($user == null){
            $product['like'] = 0;
        } else {
            $like = Favourite::where('user_id', $user->id)->where('product_id', $request->id)->first();
            if ($like) {
                $product['like'] = 1;
            } else {
                $product['like'] = 0;
            }
        }

        return view('home.products.show', compact('product', 'page'));
    }

    /**
     * get single product data, includes brand, category and favourites/likes
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function get_product(Request $request)
    {
        $user = Auth::user();
        $product = Product::find($request->id);
        $product['brand'] = Brand::find($product->brand_id);
        $product['category'] = Category::find($product->category_id);
        $like = Favourite::where('user_id', $user->id)->where('product_id', $request->id)->first();
        if ($like) {
            $product['like'] = 1;
        } else {
            $product['like'] = 0;
        }
        return response()->json($product, 200);
    }

    /**
     * update favourites
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update_like(Request $request)
    {
        $user = Auth::user();
        $favourite = Favourite::where('user_id', $user->id)->where('product_id', $request->product_id)->first();
        if ($favourite) {
            $favourite->delete();
            return response()->json('已取消收藏', 200);
        } else {
            Favourite::create(['user_id' => $user->id,
                'product_id' => $request->product_id]);
            return response()->json('收藏成功', 200);
        }
    }

    /**
     * display single product detail page
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function product_detail(Request $request)
    {
        $page = 'products';
        $product = Product::find($request->id);
        return view('home.products.detail', compact('page', 'product'));
    }

    /**
     * search product
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search_products(Request $request)
    {
        $page = 'products';
        $search_query = $request->search_query;
        if ($search_query == 'price_up') {
            $products = Product::orderBy('price')->get();
        } elseif ($search_query == 'price_down') {
            $products = Product::orderBy('price', 'desc')->get();
        } elseif ($search_query == 'sale_down') {
            $products = Product::orderBy('sale', 'desc')->get();
        } else {
            $products = Product::search($search_query)->get();
        }
        return view('home.searches.show', compact('products', 'page', 'search_query'));
    }

    /**
     * render favourite page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function favourite_index()
    {
        $page = 'dashboard';
        return view('home.favourites.index', compact('page'));
    }

    /**
     * get favourites data
     * @return \Illuminate\Http\JsonResponse
     */
    public function get_fav()
    {
        $user = Auth::user();
        $fav_products = $user->fav_products;
        return response()->json($fav_products, 200);
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('products.product_tab')
            <hr>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">添加产品</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <div class="form-group row">
                                <label for="img_url" class="col-md-4 col-form-label text-md-right">产品图片(1:1,至少600*600)</label>

                                <div class="col-md-6">
                                    <input id="img_url" type="file"
                                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                                           name="img_url" required autofocus>

                                    @if ($errors->has('img_url'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="spec" class="col-md-4 col-form-label text-md-right">规格</label>

                                <div class="col-md-6">
                                    <input id="spec" type="text"
                                           class="form-control{{ $errors->has('spec') ? ' is-invalid' : '' }}"
                                           name="spec" value="{{ old('spec') }}" required autofocus>

                                    @if ($errors->has('spec'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('spec') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">详情介绍</label>

                                <div class="col-md-6">
                                    <input id="description" type="text"
                                           class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                                           name="description" value="{{ old('description') }}" autofocus>

                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="RRP" class="col-md-4 col-form-label text-md-right">RRP价格</label>

                                <div class="col-md-6">
                                    <input id="RRP" type="number" step="0.01"
                                           class="form-control{{ $errors->has('RRP') ? ' is-invalid' : '' }}"
                                           name="RRP" value="{{ old('RRP') }}" required autofocus>

                                    @if ($errors->has('RRP'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('RRP') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">价格</label>

                                <div class="col-md-6">
                                    <input id="price" type="number" step="0.01"
                                           class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                           name="price" value="{{ old('price') }}" required autofocus>

                                    @if ($errors->has('price'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="sale_price" class="col-md-4 col-form-label text-md-right">打折价格（选填）</label>

                                <div class="col-md-6">
                                    <input id="sale_price" type="number" step="0.01"
                                           class="form-control{{ $errors->has('sale_price') ? ' is-invalid' : '' }}"
                                           name="sale_price" value="{{ old('sale_price') }}">

                                    @if ($errors->has('sale_price'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('sale_price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="reward_points" class="col-md-4 col-form-label text-md-right">积分（选填）</label>

                                <div class="col-md-6">
                                    <input id="reward_points" type="number" step="1"
                                           class="form-control{{ $errors->has('reward_points') ? ' is-invalid' : '' }}"
                                           name="reward_points" value="{{ old('reward_points') }}">

                                    @if ($errors->has('reward_points'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('reward_points') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">重量(g)</label>

                                <div class="col-md-6">
                                    <input id="weight" type="number"
                                           class="form-control{{ $errors->has('weight') ? ' is-invalid' : '' }}"
                                           name="weight" value="{{ old('weight') }}" required autofocus>

                                    @if ($errors->has('weight'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('weight') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">品牌</label>

                                <div class="col-md-6">
                                    <select id="brand_id"
                                            class="form-control{{ $errors->has('brand_id') ? ' is-invalid' : '' }}"
                                            name="brand_id" required autofocus>
                                        <option>请选择品牌</option>
                                        @foreach($brands as $brand)
                                            <option value="{{$brand->id}}" @if($brand->id == old('brand_id')) selected @endif>{{$brand->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('brand_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('brand_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">类别</label>

                                <div class="col-md-6">
                                    <select id="category_id"
                                            class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                                            name="category_id" required autofocus>
                                        <option>请选择类别</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" @if($category->id == old('category_id')) selected @endif >{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">银豹条码</label>

                                <div class="col-md-6">
                                    <input id="pospal_id" type="number"
                                           class="form-control{{ $errors->has('pospal_id') ? ' is-invalid' : '' }}"
                                           name="pospal_id" value="{{ old('pospal_id') }}">

                                    @if ($errors->has('pospal_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('pospal_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="expired_date" class="col-md-4 col-form-label text-md-right">保质期</label>

                                <div class="col-md-6">
                                    <input id="expired_date" type="text"
                                           class="form-control{{ $errors->has('expired_at') ? ' is-invalid' : '' }}"
                                           name="expired_date" value="{{ old('expired_at') }}">

                                    @if ($errors->has('expired_at'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('expired_at') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        添加
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/index_trashed.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('products.product_tab')
        </div>
    </div>
    <div class="container-fluid">
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <td>
                    <h1>名称</h1>
                </td>
                <td>
                    <h1>图片</h1>
                </td>
                <td>
                    <h1>价格</h1>
                </td>
                <td>
                    <h1>销量</h1>
                </td>
                <td>
                    <h1>显示销量</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            @foreach($products as $product)
                <tr>
                    <td><h1>{{$product['name']}}</h1></td>
                    <td class="d-flex justify-content-center"><img src="/daigou/storage/app/{{$product['img_url']}}"
                                                                   style="width:100px;height:100px"></td>
                    <td><h1>{{$product['price']}}</h1></td>
                    <td><h1>{{$product['real_sale']}}</h1></td>
                    <td><h1>{{$product['sale']}}</h1></td>
                    <td>
                        <div class="btn-group-vertical d-flex">
                            <form method="post" action="{{route('products.restore',$product['id'])}}" class="w-100">
                                @csrf
                                <button onclick="return confirm('确定要恢复产品吗')" class="btn btn-info">恢复产品</button>
                            </form>
                        </div>
                    </td>
                </tr>

            @endforeach
            </thead>
        </table>
    </div>
@endsection

resources/views/products/product_tab.blade.php
<div class="container-fluid">
    <div class="col-md-6 offset-3 btn-group d-flex" role="group">
        <a href="{{ route('products.index') }}" class="btn btn-info w-100">全部产品</a>
        <a href="{{ route('products.index_trashed') }}" class="btn btn-info w-100">已删除产品</a>
        <a href="{{ route('products.create') }}" class="btn btn-info w-100">添加产品</a>
    </div>
</div>